name: Takashi Intraday Scanner

on:
  schedule:
    - cron: "*/2 * * * *"  # runs every 2 minutes
  workflow_dispatch:      # manual run option

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Scanner
        run: node scanner.js
